// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64) && linux

package bpfprobe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type xdpTcpHandshakeVal struct {
	Tick    uint64
	Seq     uint32
	SrcAddr uint32
	SrcPort uint16
	Window  uint16
	Optlen  uint16
	IpTtl   uint8
	Options [40]uint8
	_       [1]byte
}

type xdpTlsHandshakeVal struct {
	SynSeq        uint32
	FragmentSize  uint16
	FragmentCount uint16
	RecordLen     uint16
	HelloLen      uint16
	Hello         [350]uint8
	_             [2]byte
}

// loadXdp returns the embedded CollectionSpec for xdp.
func loadXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp: %w", err)
	}

	return spec, err
}

// loadXdpObjects loads xdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpObjects
//	*xdpPrograms
//	*xdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpSpecs struct {
	xdpProgramSpecs
	xdpMapSpecs
	xdpVariableSpecs
}

// xdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpProgramSpecs struct {
	CountPackets *ebpf.ProgramSpec `ebpf:"count_packets"`
}

// xdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpMapSpecs struct {
	PktCount      *ebpf.MapSpec `ebpf:"pkt_count"`
	TcpHandshakes *ebpf.MapSpec `ebpf:"tcp_handshakes"`
	TlsHandshakes *ebpf.MapSpec `ebpf:"tls_handshakes"`
}

// xdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpVariableSpecs struct {
	DstIp   *ebpf.VariableSpec `ebpf:"dst_ip"`
	DstPort *ebpf.VariableSpec `ebpf:"dst_port"`
}

// xdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpObjects struct {
	xdpPrograms
	xdpMaps
	xdpVariables
}

func (o *xdpObjects) Close() error {
	return _XdpClose(
		&o.xdpPrograms,
		&o.xdpMaps,
	)
}

// xdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpMaps struct {
	PktCount      *ebpf.Map `ebpf:"pkt_count"`
	TcpHandshakes *ebpf.Map `ebpf:"tcp_handshakes"`
	TlsHandshakes *ebpf.Map `ebpf:"tls_handshakes"`
}

func (m *xdpMaps) Close() error {
	return _XdpClose(
		m.PktCount,
		m.TcpHandshakes,
		m.TlsHandshakes,
	)
}

// xdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpVariables struct {
	DstIp   *ebpf.Variable `ebpf:"dst_ip"`
	DstPort *ebpf.Variable `ebpf:"dst_port"`
}

// xdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpPrograms struct {
	CountPackets *ebpf.Program `ebpf:"count_packets"`
}

func (p *xdpPrograms) Close() error {
	return _XdpClose(
		p.CountPackets,
	)
}

func _XdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_bpfel.o
var _XdpBytes []byte
